const userRouter = require('./routes/users');
const cardRouter = require('./routes/cards');
###
GET http://localhost:3000/users
###
# GET http://localhost:3000/users/62bc437c3db57048e044be81
# GET http://localhost:3000/users/text

###
POST http://localhost:3000/signup
content-type: application/json

{
    "email": "https://ya.ru",
    "password": "SoBaKa77$"
}

###
GET http://localhost:3000/users/me

###
POST http://localhost:3000/signin 
Content-Type: application/json

{
    "email": "kukush5@mail.ru",
    "password": "SoBaKa77$"
}

###
POST http://localhost:3000/users 
Content-Type: application/json
{
    "name": "asdf1",
    "about": "positive dreamer",
    "avatar": "https://sdf"
}

###
POST http://localhost:3000/cards
Content-Type: application/json
{
    "name": "sdf",
    "link": "https://ya.ru/av.bmp",
}
###
PATCH http://localhost:3000/users/me
Content-Type: application/json
{
    "name": "Petyas",
    "about": "asdf"
}
###
PATCH http://localhost:3000/users/me/avatar
Content-Type: application/json
{
    "avatar": "https://asdfss.ru"
}
###
PATCH http://localhost:3000/404

###
GET http://localhost:3000/cards

###
DELETE http://localhost:3000/cards/62e93d64615de9bdd457bcf4

###
DELETE http://localhost:3000/cards/62c1187539c2a27570b106ec/likes

###
# PUT http://localhost:3000/cards/62c1187539c2a275770b06ec/likes
PUT http://localhost:3000/cards/61eade4c6d5acf558c42d9b8/likes

###
PUT http://localhost:3000/cards/62bfe8/likes

    
          
            
    

          
    
    
  
# PUT http://localhost:3000/cards//likes
# PUT http://localhost:3000/cards/text/likes
# PUT http://localhost:3000/cards/61eade4c6d5acf558c42d9b8/likes
###
# DELETE http://localhost:3000/cards/62bfdc2d8cc6ee91053982e8/likes
DELETE http://localhost:3000/cards/61eade4c6d5acf558c42d9b8/likes